### PR TITLE
Add versioning to rs_install

### PR DESCRIPTION
**Pull request by alexub**
This adds a version tag to the package in packages.yaml which support it and checks out that version during install. 

The rs_install version can be specified as a CLI arg. The version of rs_install used will not change the rs_install.py file which is run, but will govern the packages.yaml file used to specify packages and versions.

I also fixed a bug which resulted in `conda config --env --set subdir osx-64` setting the subdir for the *base* env, which broke my conda install on mac M1 and required uninstalling and reinstalling conda to fix. The solution is to`source activate rs` directly before calling `conda config`.

### CODE REVIEW

**Comment by boscoh** [comment]
Looks good so far.

**Comment by alexub** [comment]
@boscoh @jananzhu ready for review, I think.

**Comment by alexub** [comment]
noting: should change the version specification to use `=`

**Comment by alexub** [comment]
@jananzhu @boscoh I've debugged this on my laptop. I'm going to merge it, but if rs_install breaks for anyone in the near future, this PR is likely the culprit.

**Pull request merged**
